export const EMAIL_CHANGED = 'email_changed'
export const PASSWORD_CHANGED = 'password_changed'
export const LOGIN_USER = 'login_user'
export const LOGIN_USER_SUCCESS = 'login_user_success'
export const LOGIN_TOKEN_SUCCESS = 'login_token_success'
export const LOGIN_USER_FAIL = 'login_user_fail'
export const FORGOT_PASSWORD = 'forgot_password'
export const FORGOT_PASSWORD_SUCCESS = 'forgot_password_success'
export const FORGOT_PASSWORD_FAIL = 'forgot_password_fail'
export const RESET_PASSWORD = 'reset_password'
export const RESET_PASSWORD_SUCCESS = 'reset_password_success'
export const RESET_PASSWORD_FAIL = 'reset_password_fail'
export const USER_CLEAN = 'user_clean'
export const LOGOUT_USER = 'logout_user'

export const EMPLOYEE_CLEAN = 'employee_clean'

export const EMPLOYEE_UPDATE = 'employee_update'
export const EMPLOYEE_CREATE = 'employee_create'
export const EMPLOYEES_FETCH_SUCCESS = 'employees_fetch_success'
export const EMPLOYEE_SAVE_SUCCESS = 'employee_save_success'
