export const EMAIL_CHANGED = 'email_changed'
export const PASSWORD_CHANGED = 'password_changed'
export const LOGIN_USER = 'login_user'
export const LOGIN_USER_SUCCESS = 'login_user_success'
export const LOGIN_TOKEN_SUCCESS = 'login_token_success'
export const LOGIN_USER_FAIL = 'login_user_fail'
export const FORGOT_PASSWORD = 'forgot_password'
export const FORGOT_PASSWORD_SUCCESS = 'forgot_password_success'
export const FORGOT_PASSWORD_FAIL = 'forgot_password_fail'
export const RESET_PASSWORD = 'reset_password'
export const RESET_PASSWORD_SUCCESS = 'reset_password_success'
export const RESET_PASSWORD_FAIL = 'reset_password_fail'
export const USER_CLEAN = 'user_clean'
export const LOGOUT_USER = 'logout_user'

export const OPEN_CREATE_MESSAGE = 'open_create_message'
export const OPEN_SHOW_MESSAGE = 'open_show_message'
export const OPEN_MESSAGES_INBOX = 'open_messages_inbox'
export const OPEN_MESSAGES_SENT = 'open_messages_sent'
export const OPEN_MESSAGES_ARCHIVED = 'open_messages_archived'

export const OPEN_CREATE_TASK = 'open_create_task'
export const OPEN_SHOW_TASK = 'open_show_task'
export const OPEN_TASKS_INBOX = 'open_tasks_inbox'
export const OPEN_TASKS_SENT = 'open_tasks_sent'
export const OPEN_TASKS_ARCHIVED = 'open_tasks_archived'

export const OPEN_TRAININGS = 'open_trainings'
export const OPEN_SHOW_TRAINING_VIDEO = 'open_show_training_video'

export const OPEN_MANAGE_TRAININGS = 'open_manage_trainings'
export const OPEN_MANAGE_GROUPS = 'open_manage_groups'
export const OPEN_MANAGE_EMPLOYEES = 'open_manage_employees'
export const OPEN_MANAGE_ROLES = 'open_manage_roles'

export const OPEN_CREATE_ROLE = 'open_create_role'
export const OPEN_CREATE_EMPLOYEE = 'open_create_employee'
export const OPEN_CREATE_GROUP = 'open_create_group'
export const OPEN_CREATE_TRAINING = 'open_create_training'
export const OPEN_EDIT_TRAINING = 'open_edit_training'
export const OPEN_SET_NOTES_TRAINING = 'open_set_notes_training'

export const MAIN_CLEAN = 'main_clean'
